[FIX] sale_financial_risk: Use the assert_called_once() method to avoid errors in tests
Use the same method that appears in sale test: https://github.com/odoo/odoo/blob/11f702df0b8eb4186e93f713aba427b6ddcbf3b0/addons/sale/tests/test_payment_flow.py#L42

Traceback (most recent call last):
  File "/opt/odoo/auto/addons/sale_financial_risk/tests/test_payment_financial_risk.py", line 70, in test_payment_risk_bypass
    patched.assert_called_once_with(ANY, sale_order_id=ANY)
  File "/usr/local/lib/python3.10/unittest/mock.py", line 941, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/local/lib/python3.10/unittest/mock.py", line 929, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: _compute_show_tokenize_input_mapping(<ANY>, sale_order_id=<ANY>)
Actual: _compute_show_tokenize_input_mapping(payment.provider(18,), website_id=1, sale_order_id=91)